name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["NDS work requests"]
assignees:
  - haiderhalsh
  - nikola-nulogy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug
      placeholder: Tell us what happend!
      value: "A bug happened!"
    validations:
      required: true
    - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Description of steps to reproduce the behavior
      placeholder: placeholder
      value: "value"
    validations:
      required: true
    - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what should happen!
      value: "?"
    validations:
      required: true
    - type: textarea
    id: blocked
    attributes:
      label: Is your team blocked from moving forward by the bug?
      description: Is this problem blocking your team from delivering value to the customer? Is the customer impact high? [...]
      placeholder: Tell us ...
      value: "?"
    validations:
      required: true
    - type: checkboxes
    id: execution
    attributes:
      label: Who would you like to fix the bug?
      options:
        - label: Myself
        - DesignOps (is subject to availability / check current estimate completion time)
          required: true
    - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Tell us more ...
