name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["NDS work requests"]
assignees:
  - haiderhalsh
  - nikola-nulogy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug
      placeholder: Tell us what happend!
      value: "A bug happened!"
    validations:
      required: true

    attributes:
      label: Additional context
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Tell us more ...
