name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["NDS work requests"]
assignees:
  - haiderhalsh
  - nikola-nulogy
body:
  - type: markdown 
    attributes:
      value: |
        Thanks for taking the time to fill out the bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      placeholder: Tell us what happened ...
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: Walk us through steps that result in a described bug ...
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      placeholder: Tell us what should happen ...
  - type: textarea
    id: blocked
    attributes:
      label: Is your team blocked from moving forward by the bug?
      placeholder: Tell us if this problem is blocking your team from delivering value to the customer. Is the customer impact high?
  - type: checkboxes
    id: execution
    attributes:
      label: Who would you like to fix the bug?
      options:
      - label: Myself
      - label: DesignOps
      description: Please check the current DesignOps' estimated completion time before selecting
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Tell us more ...
